/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ListLeads': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AssignLead': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'VoiceBridge': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'voice.input.received'; data: never }>
    'StartCall': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ProcessVoiceInput': EventHandler<never, never>
    'ListCalls': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'EndCall': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ListTransactions': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ListSubscriptions': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'TerminateAiAgent': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'HireAiAgent': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ListAiAgents': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UpdateAiAgent': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DeleteAiAgent': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateAiAgent': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetAnalytics': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'HireAgent': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AddToCart': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetCart': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DeleteCartItem': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ListProperties': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetProperty': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateProperty': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'RegisterUser': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'LoginUser': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
}